---
env:
- PUPPET_VERSION=3.3.2
notifications:
email: false
rvm:
- 1.8.7
- 1.9.3
- 2.0.0
matrix:
  fast_finish: true
  allow_failures:
  - rvm: 2.0.0
language: ruby
before_script: "gem install --no-ri --no-rdoc bundler"
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
gemfile: Gemfile
